spring:
  datasource:
    url: jdbc:postgresql://localhost/first?currentSchema=invoicing
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    schemas: invoicing
  jpa:
    open-in-view: false

logging:
  level:
    root: INFO
    org.jdbi.sql: DEBUG
